### ISSUE TITLE
Error Trying to enter Raw Material for Process Order (ERPNext V11)

### ISSUE THREAD

**Issue by dawoodjee** [ESS-LLP/oztro#6]
Thanks for the good work.

I’m testing on V11 and getting this error when I enter Raw Material Trying to process the Process Order:

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1013, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 84, in runserverobj
    frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 42, in runserverobj
    r = doc.run_method(method, **args)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 772, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1048, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1031, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/process_manufacturing/process_manufacturing/process_manufacturing/doctype/process_order/process_order.py", line 48, in start_finish_processing
    return self.make_stock_entry(status)
  File "/home/frappe/frappe-bench/apps/process_manufacturing/process_manufacturing/process_manufacturing/doctype/process_order/process_order.py", line 183, in make_stock_entry
    stock_entry = self.set_se_items_start(stock_entry)
  File "/home/frappe/frappe-bench/apps/process_manufacturing/process_manufacturing/process_manufacturing/doctype/process_order/process_order.py", line 60, in set_se_items_start
    se = self.set_se_items(se, item, src_wh, self.wip_warehouse, False)
  File "/home/frappe/frappe-bench/apps/process_manufacturing/process_manufacturing/process_manufacturing/doctype/process_order/process_order.py", line 138, in set_se_items
    ["item_name", "stock_uom", "description", "expense_account", "buying_cost_center"])[0]
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 528, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 670, in _get_values_from_table
    as_dict=as_dict, debug=debug, update=update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 199, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1066, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 683, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'expense_account' in 'field list'")
```

**Comment by dawoodjee** [comment]
I’ve tested and found that the issue is limited to V11. It is working fine on V10.

**Comment by pjamsheer** [comment]
Thanks for reporting, fixed.

**Comment by dawoodjee** [comment]
Wow awesome. I'll test and report back
